AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-processor

  Sample SAM Template for image-processor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:

  # Original Bucket
  OriginalImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: original-bucket

  # Bucket for processed images
  ProcessedImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: processed-bucket

  # Lambda Function
  ImageProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: image_processor/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64

      # Permissions to read and write from S3 buckets
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref OriginalImagesBucket
        - S3WritePolicy:
            BucketName: !Ref ProcessedImagesBucket

      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref  OriginalImagesBucket
            Events: s3:ObjectCreated:*

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OriginalBucketName:
    Description: S3 bucket for uploads
    Value: !Ref OriginalImagesBucket
